# Ruby CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/language-ruby/

version: 2.1
executors:
  setup_rails_environment:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
commands:
  bundle_install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
jobs:
  test:
    parallelism: 1
    working_directory: ~/repo
    executor: setup_rails_environment
    steps:
      # checkout codebase from github
      - checkout
      - run: gem update bundler
      - bundle_install
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            echo $TEST_FILES

            bundle exec rake test $TEST_FILES
      - store_test_results:
          path: /tmp/test-results
workflows:
  version: 2.1
  test_suite:
    jobs:
      - test
