# Ruby CircleCI 2.0 configuration file
# https://circleci.com/docs/2.0/language-ruby/

version: 2.1

executors:
  project_container:


jobs:
  test:
    parallelism: 1
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
      # - image: circleci/postgres:9.4
    steps:
      # checkout codebase from github
      - checkout

      - run: gem update bundler
      # store bundler cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # store yarn / webpacker cache
      # - restore_cache:
      #     keys:
      #       - rails-demo-yarn-{{ checksum "yarn.lock" }}
      #       - rails-demo-yarn-
      # - run:
      #     name: Yarn Install
      #     command: yarn install --cache-folder ~/.cache/yarn
      # - save_cache:
      #     key: rails-demo-yarn-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn

      # setup db
      # - run: dockerize -wait tcp://localhost:5432 -timeout 1m # wait for db container
      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load

      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            echo $TEST_FILES

            bundle exec rake test $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results

workflows:
  version: 2.1
  test_suite:
    jobs:
      - test
